/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import Script from 'next/script';
import Head from 'next/head'
import Image from 'next/image'
import { MdChevronLeft, MdChevronRight } from "react-icons/md";
import Link from 'next/link';
import { IoIosArrowDropright } from "react-icons/io";
import { MdOutlineKeyboardArrowLeft,MdOutlineKeyboardArrowRight } from "react-icons/md";

import { useState, useEffect } from 'react';
import { Transition } from 'mdi-material-ui';

export default function Home() {
  const addImages = [
    'ADD/ADD.jpg',
    'ADD/aeroplane3.jpg',
    'ADD/LIMI.png',
    'ADD/3.jpg',
    'ADD/ADD1.jpg'

  ]
  
 

  const [current, setcurrent] = useState(0)

  const previousSlide = async() =>{
    if(current === 0) setcurrent(addImages.length - 1)
    else{
         setcurrent(current - 1)
    }
  }

  const nextSlide = async() =>{
    if(current === addImages.length - 1) setcurrent(0)
    else{
         setcurrent(current + 1)
    }
  }

  useEffect(() => {
    const timer = setTimeout(()=>{
      nextSlide()
    },4000);
  
    return () => {
      clearTimeout(timer);
    }
  }, [current])
  
  // setInterval(()=>{
  //   nextSlide()
  // },5000)
  return (
    <div>
      <Head>
        <title>Sangam Bharat Site for Buying Animals | Agriculture Equipment | Pets| Animal Accessories</title>
        <meta name="description" content="sangambharat.com | An ecommerce for Animals and pets | Generated by Sangam Infotec" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>

        <meta name="description" content="Online platform where you can sale animals like cat | dog |cows| horse| birds| buffalo| calf| sheep| goat| pets" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <div className="container px-1 md:mt-2 my-2
 mx-auto">
        <div className="  bg-white   md:mx-2 justify-center mt-1">

        <div id="slider" className='lg:h-[130px] relative flex flex-row  justify-start md:justify-start lg:justify-center xl:justify-center  z-auto scrollbar-hide overflow-x-scroll scroll whitespace-nowrap scroll-smooth'>

            <Link href={'/animals'}><div className='md:w-[130px] md:mx-8 md:h-[80px] w-[95px] h-[100px] inline-block p-2 md:p-2 m-1  md:ml-5 cursor-pointer hover:scale-105 ease-in-out duration-300 bg-white  px-2 md:pt-3  rounded-lg'>
              <img src={'animal.jpg'} className='w-full  md:h-[70px] h-[50px] rounded-sm' alt='animal' ></img>
              <p className="text-center mt-2 md:m-1 md:mt-3 text-sm font-semibold">Animals</p>
            </div></Link>
            <Link href={'/birds'}><div className='md:w-[130px] md:mx-8 md:h-[140px] w-[95px] h-[100px] inline-block p-2 md:p-2 m-1  md:ml-5 cursor-pointer hover:scale-105 ease-in-out duration-300 bg-white  px-2 md:pt-3  rounded-lg'>
              <img src={'birds.jpg'} className='w-full md:h-[70px] h-[50px] rounded-sm' alt='birds' ></img>
              <p className="text-center mt-2 md:m-1 md:mt-3 text-sm font-semibold">Birds</p>
            </div></Link>
            <Link href={'/equipments'}><div className='md:w-[130px] md:mx-8 md:h-[80px] w-[95px] h-[100px] inline-block p-2 md:p-2 m-1  md:ml-5 cursor-pointer hover:scale-105 ease-in-out duration-300 bg-white  px-2 md:pt-3  rounded-lg'>
              <img src={'fermer.jpg'} className='w-full md:h-[70px] h-[50px] rounded-sm' alt='farming' ></img>
              <p className="text-center mt-2 md:m-1 md:mt-3 md:ml-1 text-sm font-semibold">Equipments</p>
            </div></Link>
            <Link href={'/food'}><div className='md:w-[130px] md:mx-8 md:h-[140px] w-[95px] h-[100px] inline-block p-2 md:p-2 m-1  md:ml-5 cursor-pointer hover:scale-105 ease-in-out duration-300 bg-white  px-2 md:pt-3  rounded-lg'>
              <img src={'hira.png'} className='bg-white w-full md:h-[70px] h-[50px] rounded-sm' alt='pet food' ></img>
              <p className="text-center mt-2 md:m-1 md:mt-3 text-sm font-semibold">Foods</p>
            </div>
            </Link>

            <Link href={'/fertilizer'}> <div className='md:w-[130px] md:mx-8 md:h-[140px] w-[95px] h-[100px] inline-block p-2 md:p-2 m-1  md:ml-5 cursor-pointer hover:scale-105 ease-in-out duration-300 bg-white  px-2 md:pt-3  rounded-lg'>
              <img src={'ferti.jpg'} className='w-full md:h-[70px] h-[50px] rounded-sm' alt='Fertilizers' ></img>
              <p className="text-center mt-2 md:m-1 md:mt-3 text-sm font-semibold">Fertilizers</p>
            </div>
            </Link>
            <Link href={'/pesticides'}><div className='md:w-[130px] md:mx-8 md:h-[140px] w-[95px] h-[100px] inline-block p-2 md:p-2 m-1  md:ml-5 cursor-pointer hover:scale-105 ease-in-out duration-300 bg-white  px-2 md:pt-3  rounded-lg'>
              <img src={'pesti.jpg'} className='w-full md:h-[70px] h-[50px] rounded-sm' alt='Pesticides' ></img>
              <p className="text-center mt-2 md:m-1 md:mt-3 text-sm font-semibold">Pesticides</p>
            </div></Link>


          </div>

        </div>
      </div>

 

      <section className="text-gray-600 body-font overflow-hidden mx-3 mt-4">
  <div className="container  w-full  m-auto ">
    <div className="overflow-hidden relative m-auto w-full  ">
      <div className={`flex transition ease-out duration-500 xl:h-auto  `} style={{Transition:'100px'}}>
       <img src={addImages[current]} className='md:h-56 xl:h-auto max-h-56  hover:ease-in-out md:min-w-full lg:h-52 sm:h-40 h-24 m-auto w-[100]'  alt="aliya" />
       {console.log(current)}
      </div>
    
    <div className='   absolute sm:top-0 sm:h-full sm:w-full justify-between items-center flex text-white text-xl'>
    <button className='bg-white rounded-sm text-slate-800 sm:px-2 sm:py-8 p-0' onClick={previousSlide}><MdOutlineKeyboardArrowLeft></MdOutlineKeyboardArrowLeft></button>
    <button className='bg-white rounded-sm text-slate-800 sm:px-2 sm:py-8 p-0'  onClick={nextSlide}><MdOutlineKeyboardArrowRight/></button>

    </div>
    <div className="absolute bottom-1 sm:py-4 flex justify-center gap-2 w-full">
      {addImages.map((s, i)=>{
        return (
          <>
          <div
          onClick={()=>{setcurrent(i)}}
          key={"circle" + i}
          className={`rounded-full bottom-0 cursor-pointer w-2 h-2 ${ i === current ?"bg-gray-300":"bg-white"}`}>
            </div></>
        )
      })}</div>
    </div>
  </div></section>

     
    
      {/* <section className="text-gray-600 body-font">
  <div className="container px-5 py-2 mx-auto flex flex-wrap">
 
    <div className="flex flex-wrap md:-m-2 -m-1">
      <div className="flex flex-wrap w-1/2">
        <div className="md:p-2 p-1 w-1/2">
          <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/500x300"/>
        </div>
        <div className="md:p-2 p-1 w-1/2">
          <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/501x301"/>
        </div>
        <div className="md:p-2 p-1 w-full">
          <img alt="gallery" className="w-full h-full object-cover object-center block" src="https://dummyimage.com/600x360"/>
        </div>
      </div>
      <div className="flex flex-wrap w-1/2">
        <div className="md:p-2 p-1 w-full">
          <img alt="gallery" className="w-full h-full object-cover object-center block" src="https://dummyimage.com/601x361"/>
        </div>
        <div className="md:p-2 p-1 w-1/2">
          <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/502x302"/>
        </div>
        <div className="md:p-2 p-1 w-1/2">
          <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/503x303"/>
        </div>
      </div>
    </div>
  </div>
</section>  */}

<section className="text-gray-600 body-font overflow-hidden">
  <div className="container px-4 py-4 mx-auto">

    <div className="flex flex-wrap -m-4">
      <div className="p-4 xl:w-1/4 md:w-1/2 w-full">
        <div className="h-full  rounded-lg  flex flex-col relative overflow-hidden">
          <Link href={'/animals'}><img src="ADD/Animals.png" className='h-[320px] w-full' alt="" />
            </Link>     </div>
      </div>
      <div className="p-4 xl:w-1/4 md:w-1/2 w-full">
        <div className="h-full  rounded-lg  flex flex-col relative overflow-hidden">
          <Link href={'/birds'}><img src="ADD/Birds.png" className='h-[320px] w-full' alt="" />
            </Link>     </div>
      </div>
      <div className="p-4 xl:w-1/4 md:w-1/2 w-full">
        <div className="h-full  rounded-lg  flex flex-col relative overflow-hidden">
          <Link href={'/food'}><img src="ADD/TULK.png" className='h-[320px] w-full' alt="" />
            </Link>     </div>
      </div>
      <div className="p-4 xl:w-1/4 md:w-1/2 w-full">
        <div className="h-full  rounded-lg  flex flex-col relative overflow-hidden">
          <Link href={'/animals'}><img src="ADD/COW.png" className='h-[320px] w-full' alt="" />
            </Link>     </div>
      </div>
      <div className="p-4 xl:w-1/4 md:w-1/2 w-full">
        <div className="h-full  rounded-lg  flex flex-col relative overflow-hidden">
          <Link href={'/'}><img src="ADD/SULK.png" className='h-[320px] w-full' alt="" />
            </Link>     </div>
      </div>
      <div className="p-4 xl:w-1/4 md:w-1/2 w-full">
        <div className="h-full  rounded-lg  flex flex-col relative overflow-hidden">
          <Link href={'/'}><img src="ADD/Birds.png" className='h-[320px] w-full' alt="" />
            </Link>     </div>
      </div>
      <div className="p-4 xl:w-1/4 md:w-1/2 w-full">
        <div className="h-full  rounded-lg  flex flex-col relative overflow-hidden">
          <Link href={'/'}><img src="ADD/Animals.png" className='h-[320px] w-full' alt="" />
            </Link>     </div>
      </div>
      <div className="p-4 xl:w-1/4 md:w-1/2 w-full">
        <div className="h-full  rounded-lg  flex flex-col relative overflow-hidden">
          <Link href={'/'}><img src="ADD/Birds.png" className='h-[320px] w-full' alt="" />
            </Link>     </div>
      </div>
    
      
      
      
     
    </div>
  </div>
</section>

    </div>
  )
}
